# Namespace for yolo-cage
# Edit the name below to use a different namespace
apiVersion: v1
kind: Namespace
metadata:
  name: yolo-cage
  labels:
    app.kubernetes.io/name: yolo-cage
    purpose: ai-development
